name: Build cloud images for PCP CI
on:
  schedule:
    # every Saturday at 7 am UTC
    - cron:  '0 7 * * SAT'

jobs:
  build_images:
    name: Build images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [fedora30, ubuntu1804]
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Build images
      run: ./build/ci/run_script.sh build_image.sh ${{ matrix.distribution }}
      env:
        PCP_COMMIT: ${{ github.sha }}
